# Generated by Django 3.0.3 on 2020-03-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
