# Generated by Django 3.0.3 on 2020-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_DB', '0002_auto_20200312_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='birthday',
            field=models.DateField(auto_now=True),
        ),
    ]
