# Generated by Django 3.0.3 on 2020-03-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_DB', '0004_auto_20200312_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ankle',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='bicep_arm',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='calf',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='chest',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='cuff',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='head',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='knee',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='length',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='length_trouser',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='neck',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='shoulder_back',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='sleeve',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='stomach_fit',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='thigh',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='details',
            name='waist',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
