# Generated by Django 3.0.3 on 2020-05-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
